name: mentorship
description: "Mentorship project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.4.3
dependencies:
  build_runner: ^2.4.7
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.3.3
  easy_localization: ^3.0.3
  firebase_auth: null
  firebase_core: null
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.3.5
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^9.2.2
  flutter_svg: null
  fluttertoast: null
  freezed: ^2.4.5
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  google_sign_in: null
  intl: ^0.19.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  persistent_bottom_nav_bar: ^6.2.1
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.0.3
  retrofit_generator: ^8.0.4
  share_plus: ^10.0.2
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0

# Provide Google fonts
  google_fonts:

# View Toast to user
  flex_color_picker:
  dotted_border:
  image_picker:
  pin_code_fields:
  flutter_timer_countdown:
  flutter_shakemywidget:

dev_dependencies: null

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/launcher_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/launcher_icon.png"
  min_sdk_android: 21

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/banners/
    - assets/svgs/
